ap:
  igwBaseURL: "http://infra-inference-scheduling-inference-gateway-istio.llm-d-inference-scheduler.svc.cluster.local:80"
  image:
    repository: ghcr.io/llm-d/async-processor
    tag: 0.6.0
  imagePullPolicy: Always
  metrics:
    enabled: true
    port: 9090
    secure: false
  # messageQueueImpl: "redis-sortedset" # can be "redis-sortedset", "redis-pubsub", or "gcp-pubsub"
  gcpPubSub:
    enabled: false
    requestSubscriberId: ""
    resultTopicId: ""
    requestPathURL: "/v1/completions"
  redis:
    enabled: false
    # Secret containing the Redis URL (e.g. redis://user:pass@host:port/db or rediss://... for TLS)
    secretName: "redis-creds"
    secretKey: "url"
    requestPathURL: "/v1/completions"
    # For redis-sortedset
    requestQueueName: "request-sortedset"
    resultQueueName: "result-list"
