ap:
  igwBaseURL: "http://infra-inference-scheduling-inference-gateway-istio.llm-d-inference-scheduler.svc.cluster.local:80"
  image:
    repository: ghcr.io/llm-d/async-processor
    tag: 0.6.0
  imagePullPolicy: Always
  metrics:
    enabled: true
    port: 9090
    secure: false
  # messageQueueImpl: "redis-sortedset" # can be "redis-sortedset", "redis-pubsub", or "gcp-pubsub"
  gcpPubSub:
    enabled: false
    requestSubscriberId: ""
    resultTopicId: ""
    requestPathURL: "/v1/completions"
  redis:
    enabled: false
    port: 6379
    host: "redis-master.redis.svc.cluster.local"
    requestPathURL: "/v1/completions"
    # For redis-sortedset
    requestQueueName: "request-sortedset"
    resultQueueName: "result-list"
    auth:
      enabled: false
      secretName: "redis-creds"
      usernameKey: "username"
      passwordKey: "password"
