apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "async-processor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "async-processor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "async-processor.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "async-processor.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /async-processor
        args:
          {{- if .Values.ap.redis.enabled }}
          {{- if eq (.Values.ap.messageQueueImpl | default "redis-pubsub") "redis-sortedset" }}
          - --message-queue-impl=redis-sortedset
          - --redis.ss.igw-base-url={{ .Values.ap.igwBaseURL }}
          - --redis.addr
          - "{{ .Values.ap.redis.host }}:{{ .Values.ap.redis.port }}"
          - --redis.ss.request-path-url
          - "{{ .Values.ap.redis.requestPathURL }}"
          - --redis.ss.request-queue-name
          - "{{ .Values.ap.redis.requestQueueName | default "request-sortedset" }}"
          - --redis.ss.result-queue-name
          - "{{ .Values.ap.redis.resultQueueName | default "result-list" }}"
          {{- else }}
          - --message-queue-impl=redis-pubsub
          - --redis.igw-base-url={{ .Values.ap.igwBaseURL }}
          - --redis.request-path-url          
          - "{{ .Values.ap.redis.requestPathURL }}"
          - --redis.addr
          - "{{ .Values.ap.redis.host }}:{{ .Values.ap.redis.port }}"
          {{- end }}
          {{- if .Values.ap.redis.auth.enabled }}
          - --redis.user=$(REDIS_USERNAME)
          - --redis.password=$(REDIS_PASSWORD)
          {{- end }}
          {{- else if .Values.gcpPubSub.enabled  }}
          - --message-queue-impl=gcp-pubsub
          - --pubsub.igw-base-url={{ .Values.ap.igwBaseURL }}
          - --pubsub.request-subscriber-id={{ .Values.ap.gcpPubSub.requestSubscriberId }}
          - --pubsub.result-topic-id={{ .Values.ap.gcpPubSub.resultTopicId }}
          - --pubsub.request-path-url
          - "{{ .Values.ap.gcpPubSub.requestPathURL }}"
          {{- end }}
          - --metrics-endpoint-auth={{ .Values.ap.metrics.secure }}
        image: "{{ .Values.ap.image.repository }}:{{ .Values.ap.image.tag }}"
        imagePullPolicy: "{{ .Values.ap.imagePullPolicy }}"
        env:
          - name: LOG_LEVEL
            value: {{ if .Values.ap.logging }}{{ .Values.ap.logging.level | default "info" | quote }}{{ else }}"info"{{ end }}
          {{- if and .Values.ap.redis.enabled .Values.ap.redis.auth.enabled }}
          - name: REDIS_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.ap.redis.auth.secretName }}
                key: {{ .Values.ap.redis.auth.usernameKey }}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.ap.redis.auth.secretName }}
                key: {{ .Values.ap.redis.auth.passwordKey }}
          {{- end }}
        name: async-processor
      serviceAccountName: {{ include "async-processor.fullname" . }}
      terminationGracePeriodSeconds: 130
