apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "async-processor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "async-processor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "async-processor.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "async-processor.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /async-processor
        args:
          {{- if .Values.ap.redis.enabled }}
          - --redis.url=$(REDIS_URL)
          {{- if eq (.Values.ap.messageQueueImpl | default "redis-pubsub") "redis-sortedset" }}
          - --message-queue-impl=redis-sortedset
          - --redis.ss.igw-base-url={{ .Values.ap.igwBaseURL }}
          - --redis.ss.request-path-url
          - "{{ .Values.ap.redis.requestPathURL }}"
          - --redis.ss.request-queue-name
          - "{{ .Values.ap.redis.requestQueueName | default "request-sortedset" }}"
          - --redis.ss.result-queue-name
          - "{{ .Values.ap.redis.resultQueueName | default "result-list" }}"
          {{- else }}
          - --message-queue-impl=redis-pubsub
          - --redis.igw-base-url={{ .Values.ap.igwBaseURL }}
          - --redis.request-path-url
          - "{{ .Values.ap.redis.requestPathURL }}"
          {{- end }}
          {{- else if .Values.gcpPubSub.enabled  }}
          - --message-queue-impl=gcp-pubsub
          - --pubsub.igw-base-url={{ .Values.ap.igwBaseURL }}
          - --pubsub.request-subscriber-id={{ .Values.ap.gcpPubSub.requestSubscriberId }}
          - --pubsub.result-topic-id={{ .Values.ap.gcpPubSub.resultTopicId }}
          - --pubsub.request-path-url
          - "{{ .Values.ap.gcpPubSub.requestPathURL }}"
          {{- end }}
          - --metrics-endpoint-auth={{ .Values.ap.metrics.secure }}
          {{- if .Values.ap.tls.insecureSkipVerify }}
          - --tls-insecure-skip-verify=true
          {{- end }}
          {{- if .Values.ap.tls.caCertKey }}
          - --tls-ca-cert=/etc/tls/{{ .Values.ap.tls.caCertKey }}
          {{- end }}
          {{- if and .Values.ap.tls.certKey .Values.ap.tls.keyKey }}
          - --tls-cert=/etc/tls/{{ .Values.ap.tls.certKey }}
          - --tls-key=/etc/tls/{{ .Values.ap.tls.keyKey }}
          {{- end }}
        image: "{{ .Values.ap.image.repository }}:{{ .Values.ap.image.tag }}"
        imagePullPolicy: "{{ .Values.ap.imagePullPolicy }}"
        env:
          - name: LOG_LEVEL
            value: {{ if .Values.ap.logging }}{{ .Values.ap.logging.level | default "info" | quote }}{{ else }}"info"{{ end }}
          {{- if .Values.ap.redis.enabled }}
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.ap.redis.secretName }}
                key: {{ .Values.ap.redis.secretKey }}
          {{- end }}
        name: async-processor
        {{- with .Values.ap.tls.secretName }}
        volumeMounts:
          - name: tls-certs
            mountPath: /etc/tls
            readOnly: true
        {{- end }}
      serviceAccountName: {{ include "async-processor.fullname" . }}
      terminationGracePeriodSeconds: 130
      {{- with .Values.ap.tls.secretName }}
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ . }}
      {{- end }}
